#!/bin/bash

. ~/.config/i3/cores.conf

if [[ $(pgrep xautolock) ]]; then
	if [[ $BLOCK_BUTTON -eq 1 ]]; then
		pkill -9 xautolock
		pkill -9 i3lock
	fi

	echo ""
	echo ""
	echo $ativo
else
	if [[ $BLOCK_BUTTON -eq 1 ]]; then
		/usr/bin/xautolock -time 3 -locker 'i3lock-fancy -f "Droid-Sans-Mono" -t "Tela Bloqueada" -p -g -- scrot -z' -detect &
	fi

	if [[ $BLOCK_BUTTON -gt 1 ]]; then
		i3-msg -q exec 'i3lock-fancy -f "Droid-Sans-Mono" -t "Tela Bloqueada" -p -g -- scrot -z'
	fi

	echo ""
	echo ""
	echo ""
fi
