#!/bin/bash

full="Recebendo..."
short="Recebendo..."
aeroporto="${BLOCK_INSTANCE:-sbcg}"

hora="$(date +'%H')"
temperatura="$(weather-report -q -m $aeroporto | grep Temp | awk -F: '{print $2}')"
vento="$(weather-report -q -m $aeroporto | grep Wind | awk -F' ' '{print $4}')"
velocidade="$(weather-report -q -m $aeroporto | grep Wind | awk -F' ' '{print $8}')"
humidade="$(weather-report -q -m $aeroporto | grep Humid | awk -F' ' '{print $3}')"

if [[ ${humidade::2} -gt 80 ]]; then
    icon=""
else
    if [[ ${humidade::2} -gt 70 ]]; then
        icon=""
    else
    	if [[ ${humidade::2} -gt 60 ]]; then
        	icon=""
        else
			if [[ $hora -ge 06 && $hora -le 18 ]]; then
            	icon=""
			else
            	icon=""
			fi
        fi
    fi
fi

#full="$icon $temperatura° / $vento - $velocidade KM/h"
#short="$temperatura° / $vento - $velocidade KM/h"
full="$icon $temperatura°"
short="$temperatura°"

echo $full
echo $short
exit 0
