#!/bin/bash

full_text=$(amixer get Master | tail -n 1 | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ -z "$full_text" ]]; then
	notify-send "Pulseaudio" "Started"
	pulseaudio --start
fi

echo $full_text%
echo $full_text%
echo "#FFFFFF"
